version: '3.8'

services:
  db:
    image: postgres:15
    container_name: olist_db_container
    restart: always
    environment:
      POSTGRES_USER: marcel
      POSTGRES_PASSWORD: Proyecto28_password
      POSTGRES_DB: olist_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - "./csv_data:/datos"

  app:
    build: .
    container_name: olist_app_container
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://marcel:Proyecto28_password@db:5432/olist_db

volumes:
  pgdata: